package com.shop.user.center.dao;

import com.shop.user.center.model.AdminLogin;
import com.shop.user.center.model.AdminLoginExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminLoginMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    long countByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int deleteByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int insert(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int insertSelective(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    List<AdminLogin> selectByExample(AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    AdminLogin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int updateByExampleSelective(@Param("record") AdminLogin record, @Param("example") AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int updateByExample(@Param("record") AdminLogin record, @Param("example") AdminLoginExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int updateByPrimaryKeySelective(AdminLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Wed Apr 29 16:15:05 CST 2020
     */
    int updateByPrimaryKey(AdminLogin record);
}