package com.shop.user.center.model;

import java.io.Serializable;
import java.time.LocalDateTime;

public class AdminLogin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.id
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.admin
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private String admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.password
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.create_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.modify_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private LocalDateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_login.is_deleted
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin_login
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.id
     *
     * @return the value of admin_login.id
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.id
     *
     * @param id the value for admin_login.id
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.admin
     *
     * @return the value of admin_login.admin
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.admin
     *
     * @param admin the value for admin_login.admin
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setAdmin(String admin) {
        this.admin = admin == null ? null : admin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.password
     *
     * @return the value of admin_login.password
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.password
     *
     * @param password the value for admin_login.password
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.create_time
     *
     * @return the value of admin_login.create_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.create_time
     *
     * @param createTime the value for admin_login.create_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.modify_time
     *
     * @return the value of admin_login.modify_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public LocalDateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.modify_time
     *
     * @param modifyTime the value for admin_login.modify_time
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setModifyTime(LocalDateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_login.is_deleted
     *
     * @return the value of admin_login.is_deleted
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_login.is_deleted
     *
     * @param isDeleted the value for admin_login.is_deleted
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_login
     *
     * @mbg.generated Sun Apr 26 20:54:14 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", admin=").append(admin);
        sb.append(", password=").append(password);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}