server:
  port: 18082
  connection-timeout: 600000

dubbo:
  application:
    name: shop-user-client
  registry:
    address: zookeeper://62.234.105.111:2181
    timeout: 600000
  monitor:
    protocol: registry
  
spring:
  #mail:
   # host: smtp.163.com
    #username: s17695748297@163.com
    #password: OBIOLXHLVPXLPLBK
    #default-encoding: utf-8
    #port: 465
    #properties:
    #  mail.smtp.ssl.enable: true
    #  mail.smtp.auth: true
    #  mail.smtp.connectiontimeout: 50000
    #  mail.smtp.timeout: 50000
    #  mail.smtp.writetimeout: 50000
    #  mail.smtp.starttls.enabl: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/shop_user?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select now()
      idle-timeout: 600000
      auto-commit: true
      max-lifetime: 1200000
      maximum-pool-size: 15
      minimum-idle: 10
      login-timeout: 5
      validation-timeout: 5000
      connection-timeout: 30000
      read-only: false
  redis:
    database: 0
    host: 62.234.105.111
    port: 6379
    timeout: 600000
    jedis:
      pool:
        max-active: 16
        max-idle: 4 
 # rabbitmq:
 #   host: 39.100.237.144
 #   port: 5672
 #   username: guest
 #   password: guest
 #   #虚拟host 可以不设置,使用server默认host
 #   virtual-host: /
 #   #消息确认配置项
 #
 #   #确认消息已发送到交换机(Exchange)
 #   publisher-confirms: true
 #   #确认消息已发送到队列(Queue)
 #   publisher-returns: true
 # data:
 #   elasticsearch:
 #     cluster-name: elasticsearch
 #     cluster-nodes: 127.0.0.1:9300